name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
    - name: Test with gradle
      run: ./gradlew tests -x spotlessCheck
